model:
  backbone:
    target: models.backbones.clip.CLIP
    params:
      weights: "laion2b_s34b_b79k"
  neck:
    target: models.necks.clip.CLIPNeck
  head:
    target: models.heads.linear.LinearClsHead
    params:
      in_features: 512
      out_features: 17