model:
  backbone:
    target: models.backbones.clip.CLIP
    params:
      model_name: ViT-B-16
      weights: openai
      labels:
        [
          "Daffodil",
          "Snowdrop",
          "Lily Valley",
          "Bluebell",
          "Crocus",
          "Iris",
          "Tigerlily",
          "Tulip",
          "Fritillary",
          "Sunflower",
          "Daisy",
          "Colts Foot",
          "Dandelalion",
          "Cowslip",
          "Buttercup",
          "Windflower",
          "Pansy",
        ]
  neck:
    target: models.necks.clip.CLIPNeck
  head:
    target: models.heads.linear.LinearClsHead
    params:
      in_features: 512
      out_features: 17