model:
  backbone:
    target: models.backbones.clip.CLIP
    params:
      model_name: RN50-quickgelu
      weights: yfcc15m
      labels:
        [
          "Daffodil",
          "Snowdrop",
          "Lily Valley",
          "Bluebell",
          "Crocus",
          "Iris",
          "Tigerlily",
          "Tulip",
          "Fritillary",
          "Sunflower",
          "Daisy",
          "Colts Foot",
          "Dandelalion",
          "Cowslip",
          "Buttercup",
          "Windflower",
          "Pansy",
        ]
  neck:
    target: models.necks.clip.CLIPNeck
  head:
    target: models.heads.linear.MultiLinearClsHead
    params:
      in_features: 1024
      out_features: 17
      embedding_paths: [512, 512]
      dropout: 0.5