model:
  backbone:
    target: models.backbones.vit_b_16.ViT_B_16
    params:
      pretrained: True
  neck:
    target: models.necks.vit.ViTNeck
  head:
    target: models.heads.linear.LinearClsHead
    params:
      in_features: 768
      out_features: 17